# Site settings
title: flamendless # site title
description: >- # site description
  Blogs and rants about game development, tech, and programming.
lang: en-US # default lang
timezone: Asia/Philippines # set your timezone
# image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/flamendless/flamendless.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Brandon Blanker Lim-it # author name
  bio: >- # tell to the world
    Indie game developer and programmer.
  username: flamendless # author username
  github: flamendless
  twitter: flamendless
  # facebook: facebook_username
  email: flamendless8@email.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "https://flamendless.github.io"
baseurl:
permalink: /:title/
google_analytics: UA-141260881-1 # Add your GA Tracking Id
# fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
